### ISSUE TITLE
Requires tokenization

### ISSUE THREAD

**Issue by Daethyra** [Daethyra/cybersentinel#2]
use tiktoken

**Comment by kshitiz305** [comment]
Hey @Daethyra May I know something more about the issue and any plan how do you plan to implement tiktoken

**Comment by Daethyra** [comment]
- limit number of API calls based on maximum budget ($$$)
- data summarization/keyword count display
- stay within token limit of APIs

**Comment by Daethyra** [comment]
> Hey @Daethyra May I know something more about the issue and any plan how do you plan to implement tiktoken

- limit number of API calls based on maximum budget ($$$)
- data summarization/keyword count display
- stay within token limit of APIs

**Comment by Daethyra** [comment]
https://github.com/Daethyra/cybersentinel/tree/tokenization

**Comment by Daethyra** [comment]
- integrate `tokenizer.py` into the data pipeline
- - code needs adjustments for integration before testing the Docker image
- Update Dockerfile
- - Include tesseract installation
